version: '3'
services:
#  school-registration:
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
#    image: school-registration/api
#    ports:
#      - '8080:8080'
#      - '5005:5005'
#    environment:
#      - ENV_MYSQL_URL=jdbc:mysql://db:3306/school-registration?autoReconnect=true&useSSL=false
#      - ENV_MYSQL_USERNAME=school-admin
#      - ENV_MYSQL_PASSWORD=school
#      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8080 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
#      - PROFILE=dev
#    depends_on:
#      - db
  db:
    image: mysql:5.6
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=school-registration
      - MYSQL_USER=school-admin
      - MYSQL_PASSWORD=school
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql